services:
  db:
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=railflow
      - POSTGRES_DB=railflow
      - POSTGRES_PASSWORD=password
    command: ["postgres"]
