package me.danbrown.railflow.model.types;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Map;

/**
 * A Darwin Reason Code
 */
record ReasonCode(int reasonCode, String reason) {

    private static final Logger LOG = LoggerFactory.getLogger(ReasonCode.class);

    private static final Map<Integer, String> reasonCodeToReason = Map.<Integer, String>ofEntries(
            Map.entry(907, "This train has been delayed by the train departing late to maintain customer connections"),
            Map.entry(908, "This train has been delayed by the train making extra stops because a train was cancelled"),
            Map.entry(909, "This train has been delayed by the train making extra stops because of service disruption"),
            Map.entry(910, "This train has been delayed by waiting for a part of the train to be attached"),
            Map.entry(911, "This train has been delayed by a fault on a train"),
            Map.entry(912, "This train has been delayed by a problem with platform equipment"),
            Map.entry(913, "This train has been delayed by a fault on a train earlier"),
            Map.entry(914, "This train has been delayed by issues with communication systems"),
            Map.entry(915, "This train has been delayed by a problem in the depot"),
            Map.entry(916, "This train has been delayed by signalling staff being unavailable"),
            Map.entry(917, "This train has been delayed by staff training"),
            Map.entry(918, "This train has been delayed by a short-notice change to the timetable"),
            Map.entry(919, "This train has been delayed by misuse of a level crossing"),
            Map.entry(920, "This train has been delayed by a member of train crew being unavailable"),
            Map.entry(800, "This train has been delayed by high winds earlier in this train's journey"),
            Map.entry(921, "This train has been delayed by a member of train crew being unavailable earlier"),
            Map.entry(801, "This train has been delayed by high winds earlier today"),
            Map.entry(802, "This train has been delayed by expected industrial action"),
            Map.entry(803, "This train has been delayed by industrial action"),
            Map.entry(804, "This train has been delayed by lightning damaging a station"),
            Map.entry(805, "This train has been delayed by lightning damaging a train"),
            Map.entry(806, "This train has been delayed by lightning damaging equipment"),
            Map.entry(807, "This train has been delayed by lightning damaging the electricity supply"),
            Map.entry(808, "This train has been delayed by lightning damaging the signalling system"),
            Map.entry(809, "This train has been delayed by lightning damaging this train"),
            Map.entry(810, "This train has been delayed by an object being caught on the overhead electric wires"),
            Map.entry(811, "This train has been delayed by damage to the overhead electric wires"),
            Map.entry(812, "This train has been delayed by engineering works not being finished on time"),
            Map.entry(813, "This train has been delayed by forecasted slippery rails"),
            Map.entry(814, "This train has been delayed by ice preventing this train getting electricity from the third rail"),
            Map.entry(815, "This train has been delayed by ice preventing trains getting electricity from the third rail"),
            Map.entry(816, "This train has been delayed by slippery rails"),
            Map.entry(817, "This train has been delayed by slippery rails earlier in this train's journey"),
            Map.entry(818, "This train has been delayed by slippery rails earlier today"),
            Map.entry(819, "This train has been delayed by forecasted severe weather"),
            Map.entry(820, "This train has been delayed by severe weather"),
            Map.entry(700, "This train has been delayed by animals on the railway earlier today"),
            Map.entry(821, "This train has been delayed by severe weather earlier"),
            Map.entry(701, "This train has been delayed by cattle on the railway earlier today"),
            Map.entry(822, "This train has been delayed by severe weather earlier in this train's journey"),
            Map.entry(702, "This train has been delayed by horses on the railway earlier today"),
            Map.entry(823, "This train has been delayed by severe weather earlier today"),
            Map.entry(703, "This train has been delayed by sheep on the railway earlier today"),
            Map.entry(824, "This train has been delayed by a safety inspection of the track"),
            Map.entry(704, "This train has been delayed by passengers causing a disturbance on a train"),
            Map.entry(825, "This train has been delayed by a safety inspection on a train"),
            Map.entry(705, "This train has been delayed by passengers causing a disturbance on this train"),
            Map.entry(826, "This train has been delayed by a safety inspection on this train"),
            Map.entry(706, "This train has been delayed by passengers causing a disturbance earlier in this train's journey"),
            Map.entry(827, "This train has been delayed by a safety inspection of the track earlier today"),
            Map.entry(707, "This train has been delayed by passengers causing a disturbance on a train earlier today"),
            Map.entry(828, "This train has been delayed by a safety inspection on a train earlier today"),
            Map.entry(708, "This train has been delayed by a fault with the electric third rail earlier on this train's journey"),
            Map.entry(829, "This train has been delayed by a safety inspection on this train earlier in its journey"),
            Map.entry(709, "This train has been delayed by a fault with the electric third rail earlier today"),
            Map.entry(830, "This train has been delayed by a fault with the on train signalling system"),
            Map.entry(710, "This train has been delayed by damage to the electric third rail earlier on this train's journey"),
            Map.entry(831, "This train has been delayed by a fault with the radio system between the driver and the signaller"),
            Map.entry(711, "This train has been delayed by damage to the electric third rail earlier today"),
            Map.entry(832, "This train has been delayed by a fault with the signalling system"),
            Map.entry(712, "This train has been delayed by failure of the electricity supply earlier on this train's journey"),
            Map.entry(713, "This train has been delayed by failure of the electricity supply earlier today"),
            Map.entry(834, "This train has been delayed by the fire alarm sounding in a signalbox"),
            Map.entry(714, "This train has been delayed by the electricity being switched off for safety reasons earlier on this train's journey"),
            Map.entry(835, "This train has been delayed by the fire alarm sounding in the signalling centre"),
            Map.entry(715, "This train has been delayed by the electricity being switched off for safety reasons earlier today"),
            Map.entry(836, "This train has been delayed by forecasted heavy snow"),
            Map.entry(716, "This train has been delayed by urgent repairs to a bridge earlier today"),
            Map.entry(837, "This train has been delayed by heavy snow"),
            Map.entry(717, "This train has been delayed by urgent repairs to a tunnel earlier today"),
            Map.entry(838, "This train has been delayed by heavy snow earlier in this train's journey"),
            Map.entry(718, "This train has been delayed by urgent repairs to the railway earlier today"),
            Map.entry(839, "This train has been delayed by heavy snow earlier today"),
            Map.entry(719, "This train has been delayed by urgent repairs to the track earlier today"),
            Map.entry(840, "This train has been delayed by heavy snow over recent days"),
            Map.entry(720, "This train has been delayed by expected industrial action earlier today"),
            Map.entry(841, "This train has been delayed by a speed restriction"),
            Map.entry(600, "This train has been delayed by an operational incident earlier in its journey"),
            Map.entry(721, "This train has been delayed by expected industrial action yesterday"),
            Map.entry(842, "This train has been delayed by a speed restriction because of fog"),
            Map.entry(601, "This train has been delayed by an operational incident earlier today"),
            Map.entry(722, "This train has been delayed by industrial action earlier today"),
            Map.entry(843, "This train has been delayed by a speed restriction because of fog earlier on this train's journey"),
            Map.entry(602, "This train has been delayed by this train not stopping at a station it was supposed to earlier in its journey"),
            Map.entry(723, "This train has been delayed by industrial action yesterday"),
            Map.entry(844, "This train has been delayed by a speed restriction because of fog earlier today"),
            Map.entry(603, "This train has been delayed by this train not stopping at a station it was supposed to earlier today"),
            Map.entry(724, "This train has been delayed by an object being caught on the overhead electric wires earlier on this train's journey"),
            Map.entry(845, "This train has been delayed by a speed restriction because of heavy rain"),
            Map.entry(604, "This train has been delayed by this train not stopping in the correct position at a station earlier in its journey"),
            Map.entry(725, "This train has been delayed by an object being caught on the overhead electric wires earlier today"),
            Map.entry(846, "This train has been delayed by a speed restriction because of heavy rain earlier on this train's journey"),
            Map.entry(605, "This train has been delayed by this train not stopping in the correct position at a station earlier today"),
            Map.entry(726, "This train has been delayed by damage to the overhead electric wires earlier on this train's journey"),
            Map.entry(847, "This train has been delayed by a speed restriction because of heavy rain earlier today"),
            Map.entry(606, "This train has been delayed by this train's automatic braking system being activated earlier in its journey"),
            Map.entry(727, "This train has been delayed by damage to the overhead electric wires earlier today"),
            Map.entry(848, "This train has been delayed by a speed restriction because of high track temperatures"),
            Map.entry(607, "This train has been delayed by this train's automatic braking system being activated earlier today"),
            Map.entry(728, "This train has been delayed by earlier engineering works not being finished on time"),
            Map.entry(849, "This train has been delayed by a speed restriction because of high track temperatures earlier on this train's journey"),
            Map.entry(608, "This train has been delayed by a collision at a level crossing earlier today"),
            Map.entry(729, "This train has been delayed by a fault with the on train signalling system earlier on this train's journey"),
            Map.entry(609, "This train has been delayed by a collision at a level crossing yesterday"),
            Map.entry(850, "This train has been delayed by a speed restriction because of high track temperatures earlier today"),
            Map.entry(730, "This train has been delayed by a fault with the on train signalling system earlier today"),
            Map.entry(851, "This train has been delayed by a speed restriction because of high winds"),
            Map.entry(610, "This train has been delayed by a fault with barriers at a level crossing earlier today"),
            Map.entry(852, "This train has been delayed by a speed restriction because of high winds earlier on this train's journey"),
            Map.entry(611, "This train has been delayed by a fault with barriers at a level crossing yesterday"),
            Map.entry(853, "This train has been delayed by a speed restriction because of high winds earlier today"),
            Map.entry(612, "This train has been delayed by a road accident at a level crossing earlier today"),
            Map.entry(733, "This train has been delayed by a fault with the signalling system earlier on this train's journey"),
            Map.entry(854, "This train has been delayed by a speed restriction because of severe weather"),
            Map.entry(613, "This train has been delayed by a road accident at a level crossing yesterday"),
            Map.entry(734, "This train has been delayed by a fault with the signalling system earlier today"),
            Map.entry(855, "This train has been delayed by a speed restriction because of severe weather earlier on this train's journey"),
            Map.entry(614, "This train has been delayed by a road vehicle colliding with level crossing barriers earlier today"),
            Map.entry(856, "This train has been delayed by a speed restriction because of severe weather earlier today"),
            Map.entry(615, "This train has been delayed by a road vehicle colliding with level crossing barriers yesterday"),
            Map.entry(857, "This train has been delayed by a speed restriction because of snow and ice"),
            Map.entry(616, "This train has been delayed by a road vehicle damaging track at a level crossing earlier today"),
            Map.entry(737, "This train has been delayed by the fire alarm sounding in a signalbox earlier on this train's journey"),
            Map.entry(858, "This train has been delayed by a speed restriction because of snow and ice earlier on this train's journey"),
            Map.entry(617, "This train has been delayed by a road vehicle damaging track at a level crossing yesterday"),
            Map.entry(738, "This train has been delayed by the fire alarm sounding in a signalbox earlier today"),
            Map.entry(859, "This train has been delayed by a speed restriction because of snow and ice earlier today"),
            Map.entry(618, "This train has been delayed by a burst water main near the railway earlier today"),
            Map.entry(739, "This train has been delayed by the fire alarm sounding in the signalling centre earlier on this train's journey"),
            Map.entry(619, "This train has been delayed by a burst water main near the railway yesterday"),
            Map.entry(860, "This train has been delayed by a speed restriction earlier on this train's journey"),
            Map.entry(740, "This train has been delayed by the fire alarm sounding in the signalling centre earlier today"),
            Map.entry(861, "This train has been delayed by a speed restriction earlier today"),
            Map.entry(620, "This train has been delayed by a chemical spillage near the railway earlier today"),
            Map.entry(741, "This train has been delayed by attempted theft of overhead line electrification equipment earlier today"),
            Map.entry(862, "This train has been delayed by a speed restriction in a tunnel"),
            Map.entry(621, "This train has been delayed by a chemical spillage near the railway yesterday"),
            Map.entry(742, "This train has been delayed by attempted theft of overhead line electrification equipment yesterday"),
            Map.entry(863, "This train has been delayed by a speed restriction in a tunnel earlier on this train's journey"),
            Map.entry(501, "This train has been delayed by a broken down train"),
            Map.entry(622, "This train has been delayed by a fire near the railway involving gas cylinders earlier today"),
            Map.entry(743, "This train has been delayed by attempted theft of railway equipment earlier today"),
            Map.entry(864, "This train has been delayed by a speed restriction in a tunnel earlier today"),
            Map.entry(502, "This train has been delayed by a broken windscreen on the train"),
            Map.entry(623, "This train has been delayed by a fire near the railway involving gas cylinders yesterday"),
            Map.entry(744, "This train has been delayed by attempted theft of railway equipment yesterday"),
            Map.entry(865, "This train has been delayed by a speed restriction over a bridge"),
            Map.entry(503, "This train has been delayed by a shortage of trains because of accident damage"),
            Map.entry(624, "This train has been delayed by a fire near the railway suspected to involve gas cylinders earlier today"),
            Map.entry(745, "This train has been delayed by attempted theft of signalling cables earlier today"),
            Map.entry(866, "This train has been delayed by a speed restriction over a bridge earlier on this train's journey"),
            Map.entry(504, "This train has been delayed by a shortage of trains because of extra safety inspections"),
            Map.entry(625, "This train has been delayed by a fire near the railway suspected to involve gas cylinders yesterday"),
            Map.entry(746, "This train has been delayed by attempted theft of signalling cables yesterday"),
            Map.entry(867, "This train has been delayed by a speed restriction over a bridge earlier today"),
            Map.entry(505, "This train has been delayed by a shortage of trains because of vandalism"),
            Map.entry(626, "This train has been delayed by a fire on property near the railway earlier today"),
            Map.entry(747, "This train has been delayed by attempted theft of third rail electrification equipment earlier today"),
            Map.entry(868, "This train has been delayed by a speed restriction over an embankment"),
            Map.entry(506, "This train has been delayed by a shortage of trains following damage by snow and ice"),
            Map.entry(627, "This train has been delayed by a fire on property near the railway yesterday"),
            Map.entry(748, "This train has been delayed by attempted theft of third rail electrification equipment yesterday"),
            Map.entry(869, "This train has been delayed by a speed restriction over an embankment earlier on this train's journey"),
            Map.entry(507, "This train has been delayed by more trains than usual needing repairs at the same time"),
            Map.entry(628, "This train has been delayed by a gas leak near the railway earlier today"),
            Map.entry(749, "This train has been delayed by theft of overhead line electrification equipment earlier today"),
            Map.entry(508, "This train has been delayed by the train for this service having broken down"),
            Map.entry(629, "This train has been delayed by a gas leak near the railway yesterday"),
            Map.entry(509, "This train has been delayed by this train breaking down"),
            Map.entry(870, "This train has been delayed by a speed restriction over an embankment earlier today"),
            Map.entry(750, "This train has been delayed by theft of overhead line electrification equipment yesterday"),
            Map.entry(871, "This train has been delayed by a speed restriction over defective track"),
            Map.entry(630, "This train has been delayed by a road accident near the railway earlier today"),
            Map.entry(751, "This train has been delayed by theft of railway equipment earlier today"),
            Map.entry(872, "This train has been delayed by a speed restriction over defective track earlier on this train's journey"),
            Map.entry(510, "This train has been delayed by a collision between trains"),
            Map.entry(631, "This train has been delayed by a road accident near the railway yesterday"),
            Map.entry(752, "This train has been delayed by theft of railway equipment yesterday"),
            Map.entry(873, "This train has been delayed by a speed restriction over defective track earlier today"),
            Map.entry(511, "This train has been delayed by a collision with the buffers at a station"),
            Map.entry(632, "This train has been delayed by a wartime bomb near the railway earlier today"),
            Map.entry(753, "This train has been delayed by theft of signalling cables earlier today"),
            Map.entry(874, "This train has been delayed by attempted theft of overhead line electrification equipment"),
            Map.entry(512, "This train has been delayed by a derailed train"),
            Map.entry(633, "This train has been delayed by a wartime bomb near the railway yesterday"),
            Map.entry(754, "This train has been delayed by theft of signalling cables yesterday"),
            Map.entry(875, "This train has been delayed by attempted theft of railway equipment"),
            Map.entry(513, "This train has been delayed by a derailment within the depot"),
            Map.entry(634, "This train has been delayed by a wartime bomb which has now been made safe"),
            Map.entry(755, "This train has been delayed by theft of third rail electrification equipment earlier today"),
            Map.entry(876, "This train has been delayed by attempted theft of signalling cables"),
            Map.entry(514, "This train has been delayed by a low speed derailment"),
            Map.entry(635, "This train has been delayed by ambulance service dealing with an incident near the railway earlier today"),
            Map.entry(756, "This train has been delayed by theft of third rail electrification equipment yesterday"),
            Map.entry(877, "This train has been delayed by attempted theft of third rail electrification equipment"),
            Map.entry(515, "This train has been delayed by a train being involved in an accident"),
            Map.entry(636, "This train has been delayed by ambulance service dealing with an incident near the railway yesterday"),
            Map.entry(757, "This train has been delayed by vandalism at a station earlier today"),
            Map.entry(878, "This train has been delayed by theft of overhead line electrification equipment"),
            Map.entry(516, "This train has been delayed by trains being involved in an accident"),
            Map.entry(637, "This train has been delayed by emergency services dealing with an incident near the railway earlier today"),
            Map.entry(758, "This train has been delayed by vandalism at a station yesterday"),
            Map.entry(879, "This train has been delayed by theft of railway equipment"),
            Map.entry(517, "This train has been delayed by a fire at a station"),
            Map.entry(638, "This train has been delayed by emergency services dealing with an incident near the railway yesterday"),
            Map.entry(759, "This train has been delayed by vandalism of railway equipment earlier today"),
            Map.entry(518, "This train has been delayed by a fire at a station earlier today"),
            Map.entry(639, "This train has been delayed by fire brigade dealing with an incident near the railway earlier today"),
            Map.entry(519, "This train has been delayed by a landslip"),
            Map.entry(880, "This train has been delayed by theft of signalling cables"),
            Map.entry(760, "This train has been delayed by vandalism of railway equipment yesterday"),
            Map.entry(881, "This train has been delayed by theft of third rail electrification equipment"),
            Map.entry(640, "This train has been delayed by fire brigade dealing with an incident near the railway yesterday"),
            Map.entry(761, "This train has been delayed by vandalism on a train earlier today"),
            Map.entry(882, "This train has been delayed by vandalism at a station"),
            Map.entry(520, "This train has been delayed by a fire next to the track"),
            Map.entry(641, "This train has been delayed by police dealing with an incident near the railway earlier today"),
            Map.entry(762, "This train has been delayed by vandalism on a train yesterday"),
            Map.entry(883, "This train has been delayed by vandalism of railway equipment"),
            Map.entry(521, "This train has been delayed by a fire on a train"),
            Map.entry(642, "This train has been delayed by police dealing with an incident near the railway yesterday"),
            Map.entry(763, "This train has been delayed by vandalism on this train earlier today"),
            Map.entry(884, "This train has been delayed by vandalism on a train"),
            Map.entry(522, "This train has been delayed by a member of on train staff being taken ill"),
            Map.entry(643, "This train has been delayed by a boat colliding with a bridge earlier today"),
            Map.entry(764, "This train has been delayed by vandalism on this train yesterday"),
            Map.entry(885, "This train has been delayed by vandalism on this train"),
            Map.entry(523, "This train has been delayed by a shortage of on train staff"),
            Map.entry(644, "This train has been delayed by a fault with a swing bridge over a river earlier today"),
            Map.entry(765, "This train has been delayed by a fault with the electric third rail"),
            Map.entry(886, "This train has been delayed by train crew being delayed"),
            Map.entry(524, "This train has been delayed by a shortage of train conductors"),
            Map.entry(645, "This train has been delayed by a problem with a river bridge earlier today"),
            Map.entry(766, "This train has been delayed by damage to the electric third rail"),
            Map.entry(887, "This train has been delayed by train crew being delayed by service disruption"),
            Map.entry(525, "This train has been delayed by a shortage of train crew"),
            Map.entry(646, "This train has been delayed by an earlier problem with line-side equipment"),
            Map.entry(767, "This train has been delayed by failure of the electricity supply"),
            Map.entry(888, "This train has been delayed by a bridge being damaged"),
            Map.entry(526, "This train has been delayed by a shortage of train drivers"),
            Map.entry(647, "This train has been delayed by a security alert earlier today"),
            Map.entry(768, "This train has been delayed by the electricity being switched off for safety reasons"),
            Map.entry(889, "This train has been delayed by a bridge being damaged by a boat"),
            Map.entry(527, "This train has been delayed by a shortage of train guards"),
            Map.entry(648, "This train has been delayed by a fault on this train which is now fixed"),
            Map.entry(769, "This train has been delayed by urgent repairs to a bridge"),
            Map.entry(528, "This train has been delayed by a shortage of train managers"),
            Map.entry(649, "This train has been delayed by trespassers on the railway earlier in this train's journey"),
            Map.entry(529, "This train has been delayed by severe weather preventing train crew getting to work"),
            Map.entry(890, "This train has been delayed by a bridge being damaged by a road vehicle"),
            Map.entry(770, "This train has been delayed by urgent repairs to a tunnel"),
            Map.entry(891, "This train has been delayed by a bridge having collapsed"),
            Map.entry(650, "This train has been delayed by trespassers on the railway earlier today"),
            Map.entry(771, "This train has been delayed by urgent repairs to the railway"),
            Map.entry(892, "This train has been delayed by a broken rail"),
            Map.entry(530, "This train has been delayed by the train conductor being taken ill"),
            Map.entry(651, "This train has been delayed by a bicycle on the track"),
            Map.entry(772, "This train has been delayed by urgent repairs to the track"),
            Map.entry(893, "This train has been delayed by a late departure while the train was cleaned specially"),
            Map.entry(531, "This train has been delayed by the train driver being taken ill"),
            Map.entry(652, "This train has been delayed by a road vehicle blocking the railway"),
            Map.entry(773, "This train has been delayed by the emergency services dealing with an incident earlier today"),
            Map.entry(894, "This train has been delayed by a late running freight train"),
            Map.entry(532, "This train has been delayed by the train guard being taken ill"),
            Map.entry(653, "This train has been delayed by a supermarket trolley on the track"),
            Map.entry(774, "This train has been delayed by ambulance service dealing with an incident"),
            Map.entry(895, "This train has been delayed by a late running train being in front of this one"),
            Map.entry(533, "This train has been delayed by the train manager being taken ill"),
            Map.entry(654, "This train has been delayed by a train hitting an obstruction on the line"),
            Map.entry(775, "This train has been delayed by fire brigade dealing with an incident"),
            Map.entry(896, "This train has been delayed by a points failure"),
            Map.entry(534, "This train has been delayed by a passenger being taken ill at a station"),
            Map.entry(655, "This train has been delayed by a tree blocking the railway"),
            Map.entry(776, "This train has been delayed by police dealing with an incident"),
            Map.entry(897, "This train has been delayed by a power cut at the station"),
            Map.entry(535, "This train has been delayed by a passenger being taken ill on a train"),
            Map.entry(656, "This train has been delayed by an obstruction on the track"),
            Map.entry(777, "This train has been delayed by the emergency services dealing with an incident"),
            Map.entry(898, "This train has been delayed by a problem with the station lighting"),
            Map.entry(536, "This train has been delayed by a passenger being taken ill on this train"),
            Map.entry(657, "This train has been delayed by checking reports of an obstruction on the line"),
            Map.entry(778, "This train has been delayed by the fire alarm sounding at a station"),
            Map.entry(899, "This train has been delayed by a rail buckling in the heat"),
            Map.entry(537, "This train has been delayed by a passenger being taken ill at a station earlier today"),
            Map.entry(658, "This train has been delayed by this train hitting an obstruction on the line"),
            Map.entry(779, "This train has been delayed by the fire alarm sounding at a station earlier today"),
            Map.entry(538, "This train has been delayed by a passenger being taken ill on a train earlier today"),
            Map.entry(659, "This train has been delayed by a bicycle on the track earlier on this train's journey"),
            Map.entry(539, "This train has been delayed by a passenger being taken ill on this train earlier in its journey"),
            Map.entry(780, "This train has been delayed by a burst water main flooding the railway"),
            Map.entry(660, "This train has been delayed by a bicycle on the track earlier today"),
            Map.entry(781, "This train has been delayed by a river flooding the railway"),
            Map.entry(540, "This train has been delayed by a person being hit by a train"),
            Map.entry(661, "This train has been delayed by a road vehicle blocking the railway earlier on this train's journey"),
            Map.entry(782, "This train has been delayed by flood water making the railway potentially unsafe"),
            Map.entry(541, "This train has been delayed by a person being hit by a train earlier today"),
            Map.entry(662, "This train has been delayed by a road vehicle blocking the railway earlier today"),
            Map.entry(783, "This train has been delayed by flooding"),
            Map.entry(542, "This train has been delayed by a collision at a level crossing"),
            Map.entry(663, "This train has been delayed by a supermarket trolley on the track earlier on this train's journey"),
            Map.entry(784, "This train has been delayed by heavy rain flooding the railway"),
            Map.entry(543, "This train has been delayed by a fault with barriers at a level crossing"),
            Map.entry(664, "This train has been delayed by a supermarket trolley on the track earlier today"),
            Map.entry(785, "This train has been delayed by predicted flooding"),
            Map.entry(544, "This train has been delayed by a road accident at a level crossing"),
            Map.entry(665, "This train has been delayed by a train hitting an obstruction on the line earlier on this train's journey"),
            Map.entry(786, "This train has been delayed by the sea flooding the railway"),
            Map.entry(545, "This train has been delayed by a road vehicle colliding with level crossing barriers"),
            Map.entry(666, "This train has been delayed by a train hitting an obstruction on the line earlier today"),
            Map.entry(787, "This train has been delayed by a burst water main flooding the railway earlier today"),
            Map.entry(546, "This train has been delayed by a road vehicle damaging track at a level crossing"),
            Map.entry(667, "This train has been delayed by a tree blocking the railway earlier on this train's journey"),
            Map.entry(788, "This train has been delayed by a river flooding the railway earlier today"),
            Map.entry(547, "This train has been delayed by a problem currently under investigation"),
            Map.entry(668, "This train has been delayed by a tree blocking the railway earlier today"),
            Map.entry(789, "This train has been delayed by flood water making the railway potentially unsafe earlier today"),
            Map.entry(548, "This train has been delayed by a burst water main near the railway"),
            Map.entry(669, "This train has been delayed by an obstruction on the track earlier on this train's journey"),
            Map.entry(549, "This train has been delayed by a chemical spillage near the railway"),
            Map.entry(790, "This train has been delayed by flooding earlier in this train's journey"),
            Map.entry(670, "This train has been delayed by an obstruction on the track earlier today"),
            Map.entry(791, "This train has been delayed by flooding earlier today"),
            Map.entry(550, "This train has been delayed by a fire near the railway involving gas cylinders"),
            Map.entry(671, "This train has been delayed by checking reports of an obstruction on the line earlier on this train's journey"),
            Map.entry(792, "This train has been delayed by heavy rain flooding the railway earlier today"),
            Map.entry(551, "This train has been delayed by a fire near the railway suspected to involve gas cylinders"),
            Map.entry(672, "This train has been delayed by checking reports of an obstruction on the line earlier today"),
            Map.entry(793, "This train has been delayed by predicted flooding earlier today"),
            Map.entry(552, "This train has been delayed by a fire on property near the railway"),
            Map.entry(673, "This train has been delayed by this train hitting an obstruction on the line earlier in its journey"),
            Map.entry(794, "This train has been delayed by the sea flooding the railway earlier today"),
            Map.entry(553, "This train has been delayed by a gas leak near the railway"),
            Map.entry(674, "This train has been delayed by this train hitting an obstruction on the line earlier on this train's journey"),
            Map.entry(795, "This train has been delayed by thick fog"),
            Map.entry(554, "This train has been delayed by a road accident near the railway"),
            Map.entry(675, "This train has been delayed by this train hitting an obstruction on the line earlier today"),
            Map.entry(796, "This train has been delayed by thick fog earlier in this train's journey"),
            Map.entry(555, "This train has been delayed by a wartime bomb near the railway"),
            Map.entry(676, "This train has been delayed by a coach becoming uncoupled on a train"),
            Map.entry(797, "This train has been delayed by thick fog earlier today"),
            Map.entry(556, "This train has been delayed by ambulance service dealing with an incident near the railway"),
            Map.entry(677, "This train has been delayed by a coach becoming uncoupled on this train"),
            Map.entry(798, "This train has been delayed by forecasted high winds"),
            Map.entry(557, "This train has been delayed by emergency services dealing with an incident near the railway"),
            Map.entry(678, "This train has been delayed by a train not stopping at a station it was supposed to"),
            Map.entry(799, "This train has been delayed by high winds"),
            Map.entry(558, "This train has been delayed by fire brigade dealing with an incident near the railway"),
            Map.entry(679, "This train has been delayed by a train not stopping in the correct position at a station"),
            Map.entry(559, "This train has been delayed by police dealing with an incident near the railway"),
            Map.entry(680, "This train has been delayed by a train's automatic braking system being activated"),
            Map.entry(560, "This train has been delayed by a boat colliding with a bridge"),
            Map.entry(681, "This train has been delayed by an operational incident"),
            Map.entry(561, "This train has been delayed by a fault with a swing bridge over a river"),
            Map.entry(682, "This train has been delayed by this train not stopping at a station it was supposed to"),
            Map.entry(562, "This train has been delayed by a problem with a river bridge"),
            Map.entry(683, "This train has been delayed by this train not stopping in the correct position at a station"),
            Map.entry(563, "This train has been delayed by a problem with line-side equipment"),
            Map.entry(684, "This train has been delayed by this train's automatic braking system being activated"),
            Map.entry(564, "This train has been delayed by a security alert at a station"),
            Map.entry(685, "This train has been delayed by overcrowding"),
            Map.entry(565, "This train has been delayed by a security alert on another train"),
            Map.entry(686, "This train has been delayed by overcrowding as this train has fewer coaches than normal"),
            Map.entry(566, "This train has been delayed by a security alert on this train"),
            Map.entry(687, "This train has been delayed by overcrowding because an earlier train had fewer coaches than normal"),
            Map.entry(567, "This train has been delayed by a train derailment earlier today"),
            Map.entry(688, "This train has been delayed by overcrowding because of a concert"),
            Map.entry(568, "This train has been delayed by a train derailment yesterday"),
            Map.entry(689, "This train has been delayed by overcrowding because of a football match"),
            Map.entry(569, "This train has been delayed by a fault occurring when attaching a part of a train"),
            Map.entry(690, "This train has been delayed by overcrowding because of a marathon"),
            Map.entry(570, "This train has been delayed by a fault occurring when attaching a part of this train"),
            Map.entry(691, "This train has been delayed by overcrowding because of a rugby match"),
            Map.entry(571, "This train has been delayed by a fault occurring when detaching a part of a train"),
            Map.entry(692, "This train has been delayed by overcrowding because of a sporting event"),
            Map.entry(572, "This train has been delayed by a fault occurring when detaching a part of this train"),
            Map.entry(693, "This train has been delayed by overcrowding because of an earlier cancellation"),
            Map.entry(573, "This train has been delayed by a fault on a train in front of this one"),
            Map.entry(694, "This train has been delayed by overcrowding because of an event"),
            Map.entry(574, "This train has been delayed by a fault on this train"),
            Map.entry(695, "This train has been delayed by overcrowding earlier on this train's journey"),
            Map.entry(575, "This train has been delayed by this train being late from the depot"),
            Map.entry(696, "This train has been delayed by animals on the railway"),
            Map.entry(576, "This train has been delayed by trespassers on the railway"),
            Map.entry(697, "This train has been delayed by cattle on the railway"),
            Map.entry(577, "This train has been delayed by a bus colliding with a bridge"),
            Map.entry(698, "This train has been delayed by horses on the railway"),
            Map.entry(578, "This train has been delayed by a lorry colliding with a bridge"),
            Map.entry(699, "This train has been delayed by sheep on the railway"),
            Map.entry(579, "This train has been delayed by a road vehicle colliding with a bridge"),
            Map.entry(731, "This train has been delayed by a fault with the radio system between the driver and the signaller earlier on this train's journey"),
            Map.entry(580, "This train has been delayed by a bus colliding with a bridge earlier on this train's journey"),
            Map.entry(581, "This train has been delayed by a bus colliding with a bridge earlier today"),
            Map.entry(582, "This train has been delayed by a lorry colliding with a bridge earlier on this train's journey"),
            Map.entry(583, "This train has been delayed by a lorry colliding with a bridge earlier today"),
            Map.entry(100, "This train has been delayed by a broken down train"),
            Map.entry(584, "This train has been delayed by a road vehicle colliding with a bridge earlier on this train's journey"),
            Map.entry(101, "This train has been delayed by a delay on a previous journey"),
            Map.entry(585, "This train has been delayed by a road vehicle colliding with a bridge earlier today"),
            Map.entry(102, "This train has been delayed by a derailed train"),
            Map.entry(586, "This train has been delayed by a broken down train earlier today"),
            Map.entry(587, "This train has been delayed by an earlier landslip"),
            Map.entry(104, "This train has been delayed by a fire at a station"),
            Map.entry(588, "This train has been delayed by a fire next to the track earlier today"),
            Map.entry(105, "This train has been delayed by a fire at a station earlier"),
            Map.entry(589, "This train has been delayed by a fire on a train earlier today"),
            Map.entry(106, "This train has been delayed by a landslip"),
            Map.entry(107, "This train has been delayed by a line-side fire"),
            Map.entry(108, "This train has been delayed by a member of train crew being unavailable"),
            Map.entry(109, "This train has been delayed by a passenger being taken ill"),
            Map.entry(590, "This train has been delayed by a coach becoming uncoupled on a train earlier in its journey"),
            Map.entry(591, "This train has been delayed by a coach becoming uncoupled on a train earlier today"),
            Map.entry(732, "This train has been delayed by a fault with the radio system between the driver and the signaller earlier today"),
            Map.entry(592, "This train has been delayed by a coach becoming uncoupled on this train earlier in its journey"),
            Map.entry(593, "This train has been delayed by a coach becoming uncoupled on this train earlier today"),
            Map.entry(110, "This train has been delayed by a passenger having been taken ill earlier"),
            Map.entry(594, "This train has been delayed by a train not stopping at a station it was supposed to earlier in its journey"),
            Map.entry(111, "This train has been delayed by a person hit by a train"),
            Map.entry(595, "This train has been delayed by a train not stopping at a station it was supposed to earlier today"),
            Map.entry(112, "This train has been delayed by a person hit by a train earlier"),
            Map.entry(596, "This train has been delayed by a train not stopping in the correct position at a station earlier in its journey"),
            Map.entry(113, "This train has been delayed by a problem at a level crossing"),
            Map.entry(597, "This train has been delayed by a train not stopping in the correct position at a station earlier today"),
            Map.entry(114, "This train has been delayed by a problem currently under investigation"),
            Map.entry(598, "This train has been delayed by a train's automatic braking system being activated earlier in its journey"),
            Map.entry(115, "This train has been delayed by a problem near the railway"),
            Map.entry(599, "This train has been delayed by a train's automatic braking system being activated earlier today"),
            Map.entry(116, "This train has been delayed by a problem with a river bridge"),
            Map.entry(117, "This train has been delayed by a problem with line side equipment"),
            Map.entry(118, "This train has been delayed by a security alert"),
            Map.entry(119, "This train has been delayed by a train derailed earlier"),
            Map.entry(120, "This train has been delayed by a train fault"),
            Map.entry(121, "This train has been delayed by a train late from the depot"),
            Map.entry(122, "This train has been delayed by a train late from the depot earlier"),
            Map.entry(123, "This train has been delayed by a trespass incident"),
            Map.entry(124, "This train has been delayed by a vehicle striking a bridge"),
            Map.entry(125, "This train has been delayed by a vehicle striking a bridge earlier"),
            Map.entry(126, "This train has been delayed by an earlier broken down train"),
            Map.entry(128, "This train has been delayed by an earlier landslip"),
            Map.entry(129, "This train has been delayed by an earlier line-side fire"),
            Map.entry(130, "This train has been delayed by an earlier operating incident"),
            Map.entry(131, "This train has been delayed by an earlier problem at a level crossing"),
            Map.entry(132, "This train has been delayed by an earlier problem near the railway"),
            Map.entry(133, "This train has been delayed by an earlier problem with a river bridge"),
            Map.entry(134, "This train has been delayed by an earlier problem with line side equipment"),
            Map.entry(135, "This train has been delayed by an earlier security alert"),
            Map.entry(136, "This train has been delayed by an earlier train fault"),
            Map.entry(137, "This train has been delayed by an earlier trespass incident"),
            Map.entry(138, "This train has been delayed by an obstruction on the line"),
            Map.entry(139, "This train has been delayed by an obstruction on the line earlier"),
            Map.entry(735, "This train has been delayed by signalling staff being taken ill earlier on this train's journey"),
            Map.entry(140, "This train has been delayed by an operating incident"),
            Map.entry(141, "This train has been delayed by an unusually large passenger flow"),
            Map.entry(142, "This train has been delayed by an unusually large passenger flow earlier"),
            Map.entry(143, "This train has been delayed by animals on the line"),
            Map.entry(144, "This train has been delayed by animals on the line earlier"),
            Map.entry(145, "This train has been delayed by congestion caused by earlier delays"),
            Map.entry(146, "This train has been delayed by disruptive passengers"),
            Map.entry(147, "This train has been delayed by disruptive passengers earlier"),
            Map.entry(148, "This train has been delayed by earlier electrical supply problems"),
            Map.entry(149, "This train has been delayed by earlier emergency engineering works"),
            Map.entry(833, "This train has been delayed by signalling staff being taken ill"),
            Map.entry(736, "This train has been delayed by signalling staff being taken ill earlier today"),
            Map.entry(150, "This train has been delayed by earlier industrial action"),
            Map.entry(151, "This train has been delayed by earlier overhead wire problems"),
            Map.entry(152, "This train has been delayed by earlier over-running engineering works"),
            Map.entry(153, "This train has been delayed by earlier signalling problems"),
            Map.entry(154, "This train has been delayed by earlier vandalism"),
            Map.entry(155, "This train has been delayed by electrical supply problems"),
            Map.entry(156, "This train has been delayed by emergency engineering works"),
            Map.entry(157, "This train has been delayed by emergency services dealing with a prior incident"),
            Map.entry(158, "This train has been delayed by emergency services dealing with an incident"),
            Map.entry(159, "This train has been delayed by fire alarms sounding at a station"),
            Map.entry(160, "This train has been delayed by fire alarms sounding earlier at a station"),
            Map.entry(161, "This train has been delayed by flooding"),
            Map.entry(162, "This train has been delayed by flooding earlier"),
            Map.entry(163, "This train has been delayed by fog"),
            Map.entry(164, "This train has been delayed by fog earlier"),
            Map.entry(165, "This train has been delayed by high winds"),
            Map.entry(166, "This train has been delayed by high winds earlier"),
            Map.entry(167, "This train has been delayed by industrial action"),
            Map.entry(168, "This train has been delayed by lightning having damaged equipment"),
            Map.entry(169, "This train has been delayed by overhead wire problems"),
            Map.entry(170, "This train has been delayed by over-running engineering works"),
            Map.entry(171, "This train has been delayed by passengers transferring between trains"),
            Map.entry(172, "This train has been delayed by passengers transferring between trains earlier"),
            Map.entry(173, "This train has been delayed by poor rail conditions"),
            Map.entry(174, "This train has been delayed by poor rail conditions earlier"),
            Map.entry(175, "This train has been delayed by poor weather conditions"),
            Map.entry(176, "This train has been delayed by poor weather conditions earlier"),
            Map.entry(177, "This train has been delayed by safety checks being made"),
            Map.entry(178, "This train has been delayed by safety checks having been made earlier"),
            Map.entry(179, "This train has been delayed by signalling problems"),
            Map.entry(180, "This train has been delayed by snow"),
            Map.entry(181, "This train has been delayed by snow earlier"),
            Map.entry(182, "This train has been delayed by speed restrictions having been imposed"),
            Map.entry(183, "This train has been delayed by train crew having been unavailable earlier"),
            Map.entry(184, "This train has been delayed by vandalism"),
            Map.entry(185, "This train has been delayed by waiting earlier for a train crew member"),
            Map.entry(186, "This train has been delayed by waiting for a train crew member"),
            Map.entry(187, "This train has been delayed by engineering works"),
            Map.entry(900, "This train has been delayed by a railway embankment being damaged"),
            Map.entry(901, "This train has been delayed by a shortage of station staff"),
            Map.entry(902, "This train has been delayed by a tunnel being closed for safety reasons"),
            Map.entry(903, "This train has been delayed by an incident at the airport"),
            Map.entry(904, "This train has been delayed by congestion"),
            Map.entry(905, "This train has been delayed by the communication alarm being activated on a train"),
            Map.entry(906, "This train has been delayed by the communication alarm being activated on this train")
    );

    public static String getReasonFromCode(int reasonCode) {
        String reason = reasonCodeToReason.get(reasonCode);
        if (reason == null) {
            LOG.error("Unable to find reason for code {}", reasonCode);
            return "Unable to find reason for code %s".formatted(reasonCode);
        }
        return reason;
    }
}
